module Altertable
  module Adapters
    class Response
      attr_reader status: Integer
      attr_reader body: String

      def initialize: (Integer status, String body) -> void
    end

    class Base
      @base_url: String
      @timeout: Integer | Float
      @headers: ::Hash[String, String]

      def initialize: (base_url: String, timeout: Integer | Float, ?headers: ::Hash[String, String]) -> void
      def post: (String path, ?body: String?, ?params: ::Hash[Symbol | String, untyped]) -> Response
    end

    class FaradayAdapter < Base
      @conn: untyped

      def initialize: (base_url: String, timeout: Integer | Float, ?headers: ::Hash[String, String]) -> void
      def post: (String path, ?body: String?, ?params: ::Hash[Symbol | String, untyped]) -> Response

      private

      def wrap_response: (untyped resp) -> Response
    end

    class HttpxAdapter < Base
      @client: untyped

      def initialize: (base_url: String, timeout: Integer | Float, ?headers: ::Hash[String, String]) -> void
      def post: (String path, ?body: String?, ?params: ::Hash[Symbol | String, untyped]) -> Response

      private

      def wrap_response: (untyped resp) -> Response
    end

    class NetHttpAdapter < Base
      @uri: URI::HTTP | URI::HTTPS

      def initialize: (base_url: String, timeout: Integer | Float, ?headers: ::Hash[String, String]) -> void
      def post: (String path, ?body: String?, ?params: ::Hash[Symbol | String, untyped]) -> Response
    end
  end
end
