module Altertable
  @client: Client?

  def self.init: (String api_key, ?::Hash[Symbol, untyped] options) -> Client

  def self.track: (String event, String distinct_id, **untyped options) -> untyped

  def self.identify: (String user_id, **untyped options) -> untyped

  def self.alias: (String distinct_id, String new_user_id, **untyped options) -> untyped

  def self.client: () -> Client
end
